Repository/TransformableRepository.php

Delete object mehtod didn't delete items.

Fixed delete object method

---

Exception/ExporterFormatNotImplementedException.php
Exception/ExporterNotAvailableException.php
Exporter/YamlExporter.php
Repository/HttpRepository.php
Repository/RepositoryWithCredentials.php
Token/Token.php
composer.json
composer.lock

* Removed hard dep to symfony/yaml. Added as suggested.

Removed unused deps

---

Event/HttpEventRepository.php
Exception/InvalidTokenException.php
Http/GuzzleClient.php
Http/HttpRepositoryWithCredentials.php
Log/HttpLogRepository.php
Model/Item.php
Model/User.php
Query/Query.php
Repository/WithTokenTrait.php
Tests/Token/TokenTest.php
Token/Token.php
User/HttpUserRepository.php
User/InMemoryUserRepository.php
User/Interaction.php
User/UserRepository.php
WithToken.php
composer.json
composer.lock

- Some changes to make sure that user repository has sense

Added User repository

---

Config/Config.php
Config/ImmutableConfig.php
Config/Synonym.php
Repository/HttpRepository.php
Repository/InMemoryRepository.php
Repository/Repository.php
Repository/TransformableRepository.php

- Immutable Confg, designed to be immutable inside the index construction
- Config, designed to be changeable during an index lifetime

Added new config model

---

App/AppRepository.php
App/HttpAppRepository.php
Exception/ConnectionException.php
Http/Endpoints.php
Http/HttpResponsesToException.php

Solves part of https://github.com/apisearch-io/search-server/issues/45

Added get tokens endpoint

---

Query/Query.php
Query/SortBy.php
Tests/Query/QueryTest.php
Tests/Query/SortByTest.php

- Added more options for sorting
- Sort by field
- Sort by nested
- Sort by filtered nested

Refactored sorting

---

App/HttpAppRepository.php
Event/HttpEventRepository.php
Http/Endpoints.php
Http/HttpResponsesToException.php
Log/HttpLogRepository.php
Repository/HttpRepository.php
Tests/Http/EndpointsTest.php
User/HttpUserRepository.php

* Using now HttpClient Exception cacher as static method

Fixed some endpoints names

---

Exception/ConnectionException.php
Http/GuzzleClient.php
Http/HttpClient.php
Http/HttpResponsesToException.php
Tests/Http/GuzzleClientTest.php
Tests/Repository/HttpRepositoryTest.php

- Masking guzzle connect exception with this own one

Always using domain Connection exception

---

Exception/InvalidFormatException.php
Http/Endpoints.php
Model/Index.php
Repository/HttpRepository.php
Repository/InMemoryRepository.php
Repository/MockRepository.php
Repository/Repository.php
Repository/TransformableRepository.php
Tests/Model/IndexTest.php
Tests/Repository/InMemoryRepositoryTest.php

For https://github.com/apisearch-io/search-server/issues/125
- Index Model added
Tests will be added after finishing the first review.

added Index model to list the indices.

---

Query/SortBy.php
Tests/Query/SortByTest.php
composer.json

- Fixed special important issue. Score is sorted DESC, not ASC

SortBy score is never deleted from array

---

App/HttpAppRepository.php
Model/Item.php
Query/Filter.php
Query/Query.php
Query/ScoreStrategies.php
Query/ScoreStrategy.php
Query/SortBy.php
Tests/Query/QueryTest.php
Tests/Query/ScoreStrategiesTest.php
Tests/Query/ScoreStrategyTest.php
Tests/Query/SortByTest.php

- You can define several boosting items

Added more dynamic boosting configuration

---

App/DiskAppRepository.php
Config/Campaign.php
Config/Config.php
Http/GuzzleClient.php
Model/Item.php
Query/Query.php
Query/ScoreStrategy.php
Repository/DiskRepository.php
Repository/InMemoryRepository.php
Repository/WithTokenTrait.php
Result/Aggregation.php
Result/Aggregations.php
Result/Counter.php
Result/Result.php
Tests/App/AppRepositoryTest.php
Tests/App/DiskAppRepositoryTest.php
Tests/Repository/DiskRepositoryTest.php
Tests/Repository/InMemoryRepositoryTest.php
Tests/Repository/RepositoryTest.php
Url/UrlBuilder.php
User/DiskUserRepository.php
User/InMemoryUserRepository.php

- Same than in_memory ones, but saving to disk

Added disk repositories

---

Repository/DiskRepository.php
Repository/HttpRepository.php
Repository/InMemoryRepository.php
Repository/MockRepository.php
Repository/Repository.php
Repository/TransformableRepository.php

- Useful for preseted queries, defined inside Tokens

Query endpoint accepts parameters.

---

Query/Query.php
Repository/TransformableRepository.php
Result/Result.php
Tests/Query/QueryTest.php
Tests/Result/ResultTest.php

Added model for multiquery

---

Query/SortBy.php
Tests/Model/CoordinateTest.php
Tests/Query/FilterTest.php
Tests/Query/SortByTest.php
composer.json
phpunit.xml

Now the model has these plain fields
- type (field, distance, nested, score, random, function)
- field
- order
- mode
- function
- coordinate
Updated as well phpunit version

Sort by changes a little bit the format to be more comprehensive

---

Query/Range.php
Tests/Query/RangeTest.php

- Zero changed to minus-infinite

Infinite should be defined as null

---

Query/Range.php
Tests/Query/RangeTest.php

Fixed comparision, as 0 !== null

---

Query/Range.php
Tests/Query/RangeTest.php

- 0 was being considered empty on comparision
- 0 was being considered equals than NULL on assertion

Is not the same assertEquals than assertSame

---

.circleci/config.yml
Result/Result.php
Tests/Result/ResultTest.php
composer.json

- A list instead of an array
- Deprecated method getSuggests => getSuggestions and addSuggest =>
addSuggestion
- Tested suggestions format
- Added phpunit as dev-dependency

Fixed suggestions format

---

Query/Query.php
Query/ScoreStrategy.php
Tests/Query/QueryTest.php
Tests/Query/ScoreStrategiesTest.php

- Added some extra tests for boosting

Added weight score_strategy boosting
